name: smart_caption_generator
description: A modern Flutter app to generate Instagram captions from images.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  share_plus: ^10.0.2
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  mime: ^1.0.5
  http_parser: ^4.0.2
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  shared_preferences: ^2.2.2
  intl: ^0.18.1

dev_dependencies:
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
